### ISSUE TITLE
Why is `BandedMatrix` mutable?

### ISSUE THREAD

**Issue by jishnub** [JuliaLinearAlgebra/BandedMatrices.jl#291]
https://github.com/JuliaLinearAlgebra/BandedMatrices.jl/blob/731569129e873bea393f56c99ce2a58e61a6ef3c/src/banded/BandedMatrix.jl#L16

Tests for this package seem to pass even without mutability, so I wonder if this is used downstream. Immutability would presumably permit compiler optimizations.

**Comment by dlfivefifty** [comment]
I suspect it’s used in ApproxFun or InfiniteLinearAlgebra when ∞ matrices are cached and dynamically grown in inf QR. This could (and arguably should) be redesigned, eg using

https://github.com/JuliaArrays/ElasticArrays.jl

**Comment by dlfivefifty** [comment]
@jishnub  Do you feel like trying to make this change?

**Comment by jishnub** [comment]
Yes, I'll check if tests for these packages pass with this change locally

**Comment by dlfivefifty** [comment]
Actually I double checked and InfiniteLinearAlgebra.jl should be fine if `BandedMatrix` is immutable: it just uses a `CachedMatrix` for the back-end. (`CachedMatrix` could also be made immutable using ElasticArrays.jl but we can leave that for now.)

ApproxFunBase.jl has issues however: when a banded `CachedOperator` is resized it calls `pad!`:

https://github.com/JuliaApproximation/ApproxFunBase.jl/blob/defba13423935cec39c9c2a98748802c43cb85f3/src/Caching/banded.jl#L18

Which then swaps out the `data`:

https://github.com/JuliaApproximation/ApproxFunBase.jl/blob/9f8af07f7cbb23bcb13d0099eade91f605cb8be4/src/hacks.jl#L4

I think a quick fix would be to replace the `pad!` line with:
```julia
B.data = pad(B.data,min(N,2n),m)
```
since `CachedOperator` is mutable.
